SELECT URL FROM RANKING, REQUEST
WHERE REQUEST_ID=REQUEST.ID
AND REQUEST.DOMAIN_ID=1
AND RANKING>


SELECT 

Want to see all those URLs which are higher than AH ones for those keyphrases which have rankings of 10 and less for a certain month


1. SELECT DISTINCT(KEYPHRASE.ID) FROM KEYPHRASE, DOMAIN_RANKING DR WHERE MONTH(DR.TIMESTAMP)=7 and RANKING<=10 AND RANKING!=0 AND KEYPHRASE.ID=DR.KEYPHRASE_ID;




SELECT DISTINCT(URL), SUM(RANKING) TOTAL FROM RANKING WHERE MONTH(TIMESTAMP)=7 GROUP BY URL ORDER BY TOTAL ASC;


/* Show all URLs which had a ranking of 10 or under during this month and the number of times they appeared */
/* This shows the biggest competitors for the keyphrases chosen, but could be many URIs to a domain - e.g. J2Ski!!! */
SELECT DISTINCT(URL), COUNT(*) NUMBER FROM RANKING WHERE MONTH(TIMESTAMP)=8 AND YEAR(TIMESTAMP)=2010 AND RANKING<=10 and RANKING!=0 GROUP BY URL ORDER BY NUMBER ASC;



SELECT DISTINCT(URL), PHRASE, COUNT(*) NUMBER FROM RANKING, KEYPHRASE WHERE RANKING.KEYPHRASE_ID=KEYPHRASE.ID AND MONTH(TIMESTAMP)=8 AND RANKING<=10 and RANKING!=0 GROUP BY URL, PHRASE ORDER BY NUMBER ASC;


SELECT DISTINCT(URL), MONTH(TIMESTAMP) M, COUNT(*) NUMBER FROM RANKING WHERE YEAR(TIMESTAMP)=2010 AND RANKING<=10 and RANKING!=0 GROUP BY URL, MONTH(TIMESTAMP) ORDER BY M ASC;
