CREATE TABLE LEVEL
(ID int(3) auto_increment,
NAME varchar(50),
MAX_KEYPHRASES int(5),
MAX_DOMAINS int(5),
NUM_MONTHS_ACCESS int(3),
PRIMARY KEY (ID));

CREATE TABLE LEVEL_PRICE
(ID int(3) auto_increment,
LEVEL_ID int(3),
PRICE int(3),
PRICE_CURRENCY varchar(3),
PRIMARY KEY (ID));


CREATE TABLE USER_LEVEL
(ID int(10) auto_increment,
USER_ID int(10),
LEVEL_ID int(3),
START_DATE date,
END_DATE date,
IS_ACTIVE boolean,
PRIMARY KEY (ID));

INSERT INTO LEVEL (NAME, MAX_KEYPHRASES, MAX_DOMAINS, NUM_MONTHS_ACCESS) VALUES
("FREE", 5, 1, 3), ("BRONZE", 200, 1, 12), ("SILVER", 200, 5, 12), ("GOLD", 500, 25, 12);

INSERT INTO LEVEL_PRICE (LEVEL_ID, PRICE, PRICE_CURRENCY) VALUES
(1, 0, "GBP"), (2, 20, "GBP"), (3, 60, "GBP"), (4, 200, "GBP");

/* TEST DATA */
INSERT INTO USER_LEVEL (USER_ID, LEVEL_ID, START_DATE, END_DATE, IS_ACTIVE)
VALUES (2, 3, str_to_date("01/01/2010", "%d/%m/%Y"), str_to_date("31/10/2010", "%d/%m/%Y"), TRUE);
